manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: dgct
      url-base: https://github.com/dgct
    - name: badjeff
      url-base: https://github.com/badjeff
    - name: zettaface
      url-base: https://github.com/zettaface
  projects:
    - name: zmk
      remote: dgct
      import: app/west.yml
      revision: 21c0a66fe77ba0cb7e0dcb76310f466ac840cc11
    - name: kb_zmk_ps2_mouse_trackpoint_driver
      remote: dgct
      revision: 96e9cca7
    - name: zmk-input-processor-keybind
      remote: zettaface
      revision: main
  self:
    path: config
